services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: quarkus
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
    ports:
      - "5432:5432"

  quarkus-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      #- DATASOURCE_GENERATION=none
      #- DATASOURCE_SCRIPT=no-file
      - DATASOURCE_USERNAME=quarkus
      - DATASOURCE_PASSWORD=quarkus
      - DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/quarkus
    ports:
      - "8080:8080"
    depends_on:
      - postgres